name: Greeting from dkgee

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env: 
          MY_VAR: Hi there! My name is
          FIRST_NAME: Dk
          MIDDLE_NAME: The
          LAST_NAME: Gee
        run: |
          echo Hay,baby go, $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.

  repo-echo:
    name: Repo Echo
    runs-on: ubuntu-latest
    steps:
      - name: Print local repo name
        env: 
          REPO_NAME: dkgee/GithubActionLearning
        run: |
          echo Hay,dkgee, this repo name is $REPO_NAME.
