name: CI from dkgee

on: push

jobs:
  pip-job:
    name: Pip Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:           
          NAME: dkgee          
        run: |
          echo Hay, $NAME, Pip a little pip.
  
  pip2-job:
    name: Second Pip Job
    needs:
      - pip-job
    runs-on: ubuntu-latest
    steps:
      - name: Print a pip2 job
        env:           
          NAME: dkgee2          
        run: |
          echo Hay, $NAME, Pip2 a little pip.
  
  pip3-job:
    name: Third Pip Job
    needs:
      - pip2-job
    runs-on: ubuntu-latest
    steps:
      - name: Print a pip3 job
        env:           
          NAME: dkgee3          
        run: |
          echo Hay, $NAME, Pip3 a little pip.
  
  pip4-job:
    name: Four Pip Job
    needs:
      - pip2-job
      - pip3-job
    runs-on: ubuntu-latest
    steps:
      - name: Print a pip4 job
        env:           
          NAME: dkgee4          
        run: |
          echo Hay, $NAME, Pip4 a little pip.

  pip5-job:
    name: Five Pip Job
    needs:
      - pip-job
      - pip2-job
    runs-on: ubuntu-latest
    steps:
      - name: Print a pip5 job
        env:           
          NAME: dkgee5          
        run: |
          echo Hay, $NAME, Pip5 a little pip.