name: CI from dkgee

on: push

jobs:
  pip-job:
    name: Pip Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:           
          NAME: dkgee          
        run: |
          echo Hay, $NAME, Pip a little pip.